# Site settings
title: farpras
baseurl: "/blog"
url: "http://farpras.github.io"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave blank to disable it
google_analytics: 
disqus_shortname: farpras28
